services:
  front:
    build:
      context: ./501_FRONT/
      dockerfile: Dockerfile # Spécifiez le Dockerfile du front-end si nécessaire
    ports:
      - "5173:5173" # Le port sur lequel le front-end tourne
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
